export const DEFAULT_CASE = [
    {id: 34, answer: false, index: 0},
    {id: 34, answer: false, index: 1},
    {id: 34, answer: true, index: 2},
    {id: 34, answer: true, index: 3},
    {id: 34, answer: true, index: 4},
    {id: 34, answer: true, index: 5},
    {id: 33, answer: false, index: 6},
    {id: 33, answer: false, index: 7},
    {id: 33, answer: false, index: 8},
    {id: 33, answer: false, index: 9},
    {id: 33, answer: true, index: 10},
    {id: 33, answer: true, index: 11},
    {id: 33, answer: true, index: 12},
    {id: 33, answer: true, index: 13},
    {id: 33, answer: true, index: 14},
    {id: 32, answer: false, index: 15},
    {id: 32, answer: false, index: 16},
    {id: 32, answer: true, index: 17},
    {id: 32, answer: true, index: 18},
    {id: 32, answer: true, index: 19},
    {id: 34, answer: false, index: 20},
    {id: 34, answer: false, index: 21},
    {id: 34, answer: false, index: 22},
    {id: 34, answer: false, index: 23},
    {id: 34, answer: true, index: 24},
    {id: 34, answer: true, index: 25},
    {id: 34, answer: true, index: 26},
    {id: 34, answer: true, index: 27},
    {id: 34, answer: true, index: 28},
    {id: 34, answer: true},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
    {id: 35, answer: false},
]